"""PrimerRespaldo

Revision ID: 690ae1c0cfd2
Revises: 2323bcae1121
Create Date: 2025-05-17 23:26:31.758030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690ae1c0cfd2'
down_revision: Union[str, None] = '2323bcae1121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fabricante', sa.VARCHAR(length=50), nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modelo')
    )
    # ### end Alembic commands ###
