"""Mucho-Mucho-cambiado

Revision ID: 2112be5fa7b7
Revises: c87fa7ccd0a2
Create Date: 2025-05-19 21:19:56.930907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2112be5fa7b7'
down_revision: Union[str, None] = 'c87fa7ccd0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispositivos_grupos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispositivos_grupos',
    sa.Column('dispositivo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grupo_dispositivo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos.id'], name='dispositivos_grupos_dispositivo_id_fkey'),
    sa.ForeignKeyConstraint(['grupo_dispositivo_id'], ['grupos_dispositivos.id'], name='dispositivos_grupos_grupo_dispositivo_id_fkey'),
    sa.PrimaryKeyConstraint('dispositivo_id', 'grupo_dispositivo_id', name='dispositivos_grupos_pkey')
    )
    # ### end Alembic commands ###
