"""relaciones-listas

Revision ID: c87fa7ccd0a2
Revises: 
Create Date: 2025-05-18 18:47:51.940464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87fa7ccd0a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos_dispositivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_dispositivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fabricante', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modelo')
    )
    op.create_table('dispositivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(length=50), nullable=False),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('version_firmware', sa.String(length=50), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('tipo_dispositivo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_dispositivo_id'], ['tipos_dispositivos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_table('dispositivos_grupos',
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('grupo_dispositivo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos.id'], ),
    sa.ForeignKeyConstraint(['grupo_dispositivo_id'], ['grupos_dispositivos.id'], ),
    sa.PrimaryKeyConstraint('dispositivo_id', 'grupo_dispositivo_id')
    )
    op.create_table('logs_estado_dispositivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('mensaje_opcional', sa.String(length=200), nullable=True),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_sensor', sa.String(length=50), nullable=False),
    sa.Column('unidad_medida', sa.String(length=20), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecturas_datos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('valor_leido', sa.String(length=50), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecturas_datos')
    op.drop_table('sensores')
    op.drop_table('logs_estado_dispositivo')
    op.drop_table('dispositivos_grupos')
    op.drop_table('dispositivos')
    op.drop_table('tipos_dispositivos')
    op.drop_table('grupos_dispositivos')
    # ### end Alembic commands ###
