"""DB-v2

Revision ID: 7f8f268c84ab
Revises: a0d479e947b1
Create Date: 2025-05-25 20:35:46.613229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8f268c84ab'
down_revision: Union[str, None] = 'a0d479e947b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensores', sa.Column('umbral_alerta', sa.Float(), nullable=True))

    op.add_column('dispositivos', sa.Column('estado_actual', sa.String(length=20), nullable=True))

    op.alter_column(
        'dispositivos',
        'ubicacion',
        new_column_name='descripcion_ubicacion',
        existing_type=sa.String(length=200)
    )
    
    op.add_column('dispositivos', sa.Column('coordenadas_gps', sa.String(length=50), nullable=True))
    
    op.execute("""
        UPDATE dispositivos SET estado_actual = sub.estado FROM (
            SELECT dispositivo_id, estado
            FROM logs_estado_dispositivo
            WHERE (dispositivo_id, timestamp) IN (
                SELECT dispositivo_id, MAX(timestamp)
                FROM logs_estado_dispositivo
                GROUP BY dispositivo_id
            )
        ) AS sub
        WHERE dispositivos.id = sub.dispositivo_id;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensores', 'umbral_alerta')
    op.drop_column('dispositivos', 'estado_actual')
    op.drop_column('dispositivos', 'coordenadas_gps')

    op.alter_column(
        'dispositivos',
        'descripcion_ubicacion',
        new_column_name='ubicacion',
        existing_type=sa.String(length=200)
    )
    # ### end Alembic commands ###
